spring.application.name=trackmint
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/trackmint
#spring.datasource.url=jdbc:postgresql://db:5432/trackmint
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=OWRuPuRF88uD0Ysh+LtKyDs1g74Eb8NoRKa06Emf1Ao=
jwt.expiration=3600000